# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0d8c1998c2adadb96b5879fba9227c5c68b141b4504521b7be02321ecbb5dd6c2266ab572318661dc629850ddf3fe06931b3e516b99557699caa55292081dd8c

test:
  secret_key_base: 579295705e9fe2456a95c2ff01b20c863631841f7107500a2989cae63d6b245904af468fcc63f0a0ed7168da872b14884fa59a237ac951390bc6bbf6bf85de7a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
